### PR TITLE
Blender4

### PR DESCRIPTION
**Pull request by josuemtzmo**
Add support for blender 4

### CODE REVIEW

**Comment by josuemtzmo** [comment]
Test to add: 

- [ ] Implement test in blender > 4.0
- [ ] Improve coverage in Blender 4.0

**Comment by orioltinto** [comment]
Hi @josuemtzmo , I was testing if I could use this branch and it is mostly working with Blender 4.1 on windows. I only had an issue because the render of animations was hanging. Removing the update_all_images handler from the render_pre solved the issue. I tried it in Linux as well and I think it works. Do you think I should update this change to this branch?

**Comment by josuemtzmo** [comment]
Yes, you can directly edit this PR?

**Comment by josuemtzmo** [comment]
I still think that `update_all_images` should be supported, because it's the code that updates the images when the nodes are updated.

**Comment by josuemtzmo** [comment]
Are the images you are testing with large? If it is hanging it may be because of that?

**Comment by orioltinto** [comment]
Hi @josuemtzmo , in that case the images were not really big. In the current code we have:

In  [blendernc.py](https://github.com/blendernc/blendernc/blob/545dec6ac3a78858d443d63dabe60b43b775df13/blendernc/blendernc.py#L130C1-L132C44) we have:
```
    handlers.frame_change_pre.append(**bpy.types.Scene.update_all_images**)
    handlers.render_pre.append(**bpy.types.Scene.update_all_images**)
    handlers.load_post.append(load_handler)
```    

so the update_all_images is added to frame_change_pre and render_pre.
Leaving only frame_change_pre worked for me.
I don't remember why this was necessary in the first place, but maybe I can make this call version dependent.

**Pull request merged**
