### PR TITLE
Implement BlenderNC_NT_tutorial

### PR DESCRIPTION
**Pull request by josuemtzmo**
Road to docs!

### CODE REVIEW

**Comment by josuemtzmo** [comment]
To do:

- [ ] Break CI into more sections to easier interpretation.
- [ ] Hide Cycles render output.

**Comment by josuemtzmo** [comment]
@whatnick have you implemented coverage with unittest? I've attempted it using:

https://coverage.readthedocs.io/en/coverage-5.5/subprocess.html

but I haven't manage to produce a report.

**Comment by whatnick** [comment]
https://pypi.org/project/pytest-blender/

**Comment by josuemtzmo** [comment]
@whatnick, I solved the issue by doing a `coverage combine` after running the tests. 

https://github.com/blendernc/blendernc/blob/c1528c81b19e1f09408e81adc6a915e60b7b6109/tests/build-test.sh#L20-L28

**Pull request merged**
