### PR TITLE
Increase maintainability 

### PR DESCRIPTION
**Pull request by josuemtzmo**
**This doesn't affect any of the user interactions.**

In order to simplify development, over several PR's complexity of functions will be reduced, and files will only be allowed to have up to 450 lines.

### CODE REVIEW

**Comment by josuemtzmo** [comment]
This increases maintainability to **A**, however, further changes in following PRs will solve all ongoing complexity issues.

**Comment by josuemtzmo** [comment]
@whatnick Do you have any suggestion on this regard?

**Comment by whatnick** [comment]
Most of the complexity issues reported by codeclimate are just python syntax complexity. I am happy with gradual reduction rather than overcommiting to what we have. Let us now increase complexity knowingly and run the complexity check in pre-commit if possible. You can install McCabe from PyCQA on top of Flake8 : https://github.com/PyCQA/mccabe

**Review by whatnick — APPROVED** [review]

**Comment by josuemtzmo** [comment]
Excellent Idea, I will create a new PR to implement McCabe!

**Pull request merged**
