### PR TITLE
Implement dask client.

### PR DESCRIPTION
**Pull request by josuemtzmo**
Improvements:
- Support for dask client.
- Add useful links in user preferences. 

Within the node tree, the `dask` dashboard is displayed.

Screen Shot 2021-07-24 at 6 56 38 pm

The user preference allows the user to initiate **blenderNC** using `dask`.
Screen Shot 2021-07-24 at 6 56 59 pm

### CODE REVIEW

**Comment by josuemtzmo** [comment]
Coverage will drop, as many of the implementations require changes in the user interface. However, changing the preference `blendernc_use_dask` is now tested.

**Review by whatnick — CHANGES_REQUESTED** [review]
Dask worker temp files are checked in..please add these to .gitignore and git rm here.

**Comment by josuemtzmo** [comment]
Thanks, I completely forgot to remove them!

**Comment by josuemtzmo** [comment]
I removed the testing of `dask`, as currently running `dask` in background mode will generate the following issue, as a consequence of multiprocessing modifying the `sys.path`. 

``` 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/bin/2.92/python/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/bin/2.92/python/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/bin/2.92/python/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/bin/2.92/python/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/bin/2.92/python/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/bin/2.92/python/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/bin/2.92/python/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/blendernc/tests/blendernc_nodetree_settings.test1.py", line 6, in <module>
    import bpy
  File "/bin/2.92/scripts/modules/bpy/__init__.py", line 38, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from _bpy import (
ModuleNotFoundError: No module named '_bpy'
```
I will look more into this, but I believe there will be no way to test this soon. A really interesting discussion on this issue can be found at: 
https://github.com/TylerGubala/blenderpy/issues/23

**Comment by josuemtzmo** [comment]
I figured that if the `dask.Distributed.Client` is initiated with the `processes=False` flag, then the issues disappear. This also solves *BlenderNC* crashing within the UI when loading a dataset and creating forks of the child processes.

**Review by whatnick — APPROVED** [review]

**Pull request merged**
