### PR TITLE
Support Grib formats via Python CFGrib library

### PR DESCRIPTION
**Pull request by whatnick**
- [x] Refactor from `load_netcdf` to `load_datacube`
- [x] Refactor from `check_netcdf` to `check_datacube`

This work is partial implementation for #43 and in response to ESOWC Challenge - https://github.com/esowc/challenges_2021/issues/4

### CODE REVIEW

**Comment by whatnick** [comment]
@josuemtzmo could we please disable travis and merge this as is and continue more changes as smaller increments ?

**Comment by whatnick** [comment]
@josuemtzmo this is now ready to review and merge.

**Comment by josuemtzmo** [comment]
I will wait to merge until we figure out how to load `cfgrib` in the blender python distribution, as currently it is not supported.

**Comment by josuemtzmo** [comment]
TODO:

- [ ] Get grib example file to include cfgrib file import and test. @StephanSiemen, could you save and share 5 days from the example data that Sylvie shared with us? I tried using `from cfgrib.xarray_to_grib import to_grib` but it fails, I will submit an issue to cfgrib tomorrow. 
- [ ]  zarr support. Fix bug, where blenderNC expects a file, and raises the error `file doesn't exist`. This is a consequence of `zarr` using a folder structure instead of a file.

**Comment by whatnick** [comment]
I believe support for Zarr should be done separately in the spirit of "small changes delivered continuously" - https://martinfowler.com/bliki/ContinuousDelivery.html

**Pull request merged**
