### PR TITLE
Road to 0.4.0

### PR DESCRIPTION
**Pull request by josuemtzmo**

### CODE REVIEW

**Comment by josuemtzmo** [comment]
The commit https://github.com/blendernc/blendernc/pull/101/commits/40b64ea1b136f4c3516a3215d84ec67212d6777b allows users to change the default nodetree "BlenderNC" to anything when loading a new file.

**Comment by whatnick** [comment]
Large PR's like these are impossible to review in a meaningful way. I would approve blindly and trust the CI and user testing. After this major bump, let us do incremental changes and less cognitive load on reviews.

**Comment by josuemtzmo** [comment]
> Large PR's like these are impossible to review in a meaningful way. I would approve blindly and trust the CI and user testing. After this major bump, let us do incremental changes and less cognitive load on reviews.

I agree I did several PRs and merges to `dev`, but it got out of control. I don't want to change `master`, other than in releases.

**Comment by whatnick** [comment]
Ah yes we need discuss trunk based development.

https://trunkbaseddevelopment.com/

**Comment by josuemtzmo** [comment]
@whatnick, could you try to play with this version? I know reviewing is irrelevant ATM, but could follow the tutorials I've created to check everything is working...

**Comment by whatnick** [comment]
> @whatnick, could you try to play with this version? I know reviewing is irrelevant ATM, but could follow the tutorials I've created to check everything is working...
> 
> Particularly because I renamed all the API to use `datacube` instead of `netcdf` or `nc`.

Planning to do this today.

**Comment by josuemtzmo** [comment]
Ok, I will wait to hear back from you to merge it.

**Comment by whatnick** [comment]
@josuemtzmo Looks good let's merge :) Release Early, Release Often.

**Review by whatnick — APPROVED** [review]

**Comment by josuemtzmo** [comment]
Excellent! Thanks for having a look into it @whatnick!

**Pull request merged**
