### PR TITLE
Include complexity test and implement issue template.

### PR DESCRIPTION
**Pull request by josuemtzmo**
This PR will resolve complexity issues using `mccabe`, in addition, to implement an issue template.

### CODE REVIEW

**Comment by josuemtzmo** [comment]
@whatnick Can you add the `Contribution.md` you mentioned a while ago into this PR? or modify the `help.rst` contribution documentation in `readthedocs`.

**Review by whatnick — APPROVED** [review]

**Comment by josuemtzmo** [comment]
@whatnick The last push finally implement and fixed some of the issues introduced while simplifying the code. Could you have a play with it, or test it within the animations or `.blend` files you have?

**Comment by josuemtzmo** [comment]
Otherwise, I will play with it tomorrow and merge it afterwards.

**Comment by whatnick** [comment]
Starting at new position today. Time will be scarce. Will try to wedge it
in, late at night.

**Comment by josuemtzmo** [comment]
I've tested the features that have been fixed, thus I will merge them to master.

**Comment by whatnick** [comment]
Sounds good !!

**Pull request merged**
